# Location: ~/.config/alacritty/alacritty.toml

[general]
live_config_reload = false
ipc_socket = false # Unused.

[window]
dimensions = { columns = 100, lines = 36 }
dynamic_title = true

[scrolling]
history = 0 # Using Tmux for this.

[font]
normal = { family = "Fira Code", style = "Retina" }
# TODO: determine if this is still what I want.
#bold = { style = "Medium" }
#italic = { style = "Light" }
#bold_italic = { style = "Medium" }
size = 13

[colors]
draw_bold_text_with_bright_colors = true
primary = { background = "0xffd7af", foreground = "0x3c3836" }

[colors.normal]
black = "0xfbf1c7"
red = "0xcc241d"
green = "0x98971a"
yellow = "0xd79921"
blue = "0x458588"
magenta = "0xb16286"
cyan = "0x689d6a"
white = "0x7c6f64"

[colors.bright]
black = "0x928374"
red = "0x9d0006"
green = "0x79740e"
yellow = "0xb57614"
blue = "0x076678"
magenta = "0x8f3f71"
cyan = "0x427b58"
white = "0x3c3836"

[bell]
duration = 0 # Disable.

[terminal]
shell = { program = "/opt/homebrew/bin/tmux", args = ["new-session", "-A", "-t" ,"main", "-s", "main"] }
osc52 = "Disabled"
